# application-secret.properties
google.gemini.api-key=AIzaSyDIaBR4XhdZr8fFn6QhxCsg3PKB8vxum5w
maps.api.key=AIzaSyAodXJYtc0PEF9I0pECebmRvpY6iB5DazU
rapidapi.key=505ccd917emshb7a72eed3ad609fp14e458jsnd0ef49c479a0

