# application-secret.properties
google.gemini.api-key=AIzaSyCjlMRxRUNoTwV-NhOdqI0JPbOzxpSMpdk
maps.api.key=AIzaSyCnayP0y0WUVyKoH0V--DvO2lcXr7dzHjw
rapidapi.key=c9697aa007msh5841f2e5ead4d20p1c65bajsn06a2c9455e1a

