# application-secret.properties
google.gemini.api-key=AIzaSyDIaBR4XhdZr8fFn6QhxCsg3PKB8vxum5w
maps.api.key=AIzaSyC9lC2ssWsjGEhiR59LrWd-vbF7aTOfMJQ
rapidapi.key=098e58b38bmsh0b8d5f547291d42p11c333jsnd46b259e58a7

